name: CI

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.1"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download definition files
        shell: bash
        run: |
          curl -O https://github.com/JohnnyMorganz/luau-lsp/raw/main/scripts/globalTypes.d.lua
          curl -O https://gist.github.com/zxibs/81fc195db5e0e374c63b98c262b99e1d/raw/9fa3dd6e1d9f65733c1b00fef092ecbf782b8d44/utils.d.lua

      - name: Analyze
        shell: bash
        run: |
          rojo sourcemap default.project.json --output sourcemap.json
          luau-lsp analyze --no-strict-dm-types --sourcemap=sourcemap.json --definitions=globalTypes.d.lua --definitions=utils.d.lua --base-luaurc=.luaurc --ignore=Packages/** src/
        