name: Install dependencies

on: workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: baptiste0928/cargo-install@v2
        with:
          crate: wally-package-types
          version: "^1"

      - name: Install dependencies using wally
        shell: bash
        run: |
          rm -f wally.lock
          wally install

      - name: Fix luau types
        shell: bash
        run: |
          rojo sourcemap default.project.json --output sourcemap.json
          wally-package-types --sourcemap sourcemap.json Packages/

      - name: Push changes
        shell: bash
        run: |
          rm -rf .foreman-install
          git config --global user.name 'github-actions'
          git add -A || echo 'No changes to add'
          git commit -m "Installed dependencies" || echo 'No changes to commit'
          git push || echo 'No changes to push'
